# Configuração de Segurança do GitHub
security_and_analysis:
  # Habilitar análise de segurança
  advanced_security:
    status: enabled
  # Habilitar verificação de dependências
  dependency_review:
    status: enabled
  # Habilitar verificação de segredos
  secret_scanning:
    status: enabled
  # Habilitar verificação de vulnerabilidades
  vulnerability_scanning:
    status: enabled

# Configurações de branch protection
branch_protection_rules:
  - pattern: main
    enforce_admins: true
    required_status_checks:
      strict: true
      contexts:
        - "lint"
        - "test"
        - "build"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    restrictions:
      users: []
      teams: [] 